#!/usr/bin/env bash
# Run h2spec (https://github.com/summerwind/h2spec) against postrust-proxy's
# h2c listener.
#
# h2spec is an HTTP/2 conformance suite. It speaks h2 directly to the proxy, so
# what it exercises is the listener's HTTP/2 handling -- framing, flow control,
# HPACK, stream state -- and not the upstream leg, which postrust always speaks
# as HTTP/1.1. Expect broad passes, because the h2 implementation underneath is
# hyper's. The value is in catching places where our own wiring breaks h2
# semantics: that is exactly what happened when the forwarded request kept its
# HTTP/2 version and every h2c request became a 502.
#
# The proxy runs natively and only h2spec runs in Docker, reaching the host via
# host.docker.internal, so no Rust image build is needed.
#
# Usage:
#   scripts/h2spec/run.sh                 # whole suite
#   scripts/h2spec/run.sh http2/6.9       # one section
#   scripts/h2spec/run.sh --strict
#   PORT=19080 scripts/h2spec/run.sh
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
PORT="${PORT:-19080}"
# h2spec targets the dedicated HTTP/2-only listener by default. The shared
# port sniffs h1 vs h2c, so it cannot answer an invalid preface with GOAWAY
# (section 3.5); a port that only ever speaks HTTP/2 can. Set H2_PORT= empty
# to aim at the shared port instead and see the difference.
H2_PORT="${H2_PORT-19081}"
ORIGIN_PORT="${ORIGIN_PORT:-19001}"
IMAGE="${H2SPEC_IMAGE:-summerwind/h2spec:latest}"
WORK="$HERE/.work"

die() { printf 'error: %s\n' "$1" >&2; exit 1; }
stage() { printf '\n==> %s\n' "$1"; }

command -v docker >/dev/null || die "docker not found"
mkdir -p "$WORK"

cleanup() {
    for f in proxy origin; do
        if [ -f "$WORK/$f.pid" ]; then
            kill "$(cat "$WORK/$f.pid")" 2>/dev/null
            rm -f "$WORK/$f.pid"
        fi
    done
}
trap cleanup EXIT

stage "Building postrust-proxy"
( cd "$ROOT" && cargo build -p postrust-proxy 2>&1 | tail -3 ) || die "build failed"
BIN="$ROOT/target/debug/postrust-proxy"
[ -x "$BIN" ] || die "no binary at $BIN"

stage "Starting origin on 127.0.0.1:$ORIGIN_PORT"
python3 "$HERE/origin.py" "$ORIGIN_PORT" >"$WORK/origin.log" 2>&1 &
echo $! > "$WORK/origin.pid"
disown

cat > "$WORK/h2spec.toml" <<TOML
# Generated by scripts/h2spec/run.sh
[server]
http_host = "0.0.0.0"
http_port = $PORT
${H2_PORT:+http2_port = $H2_PORT}

[[upstreams]]
name = "origin"

[[upstreams.backends]]
address = "127.0.0.1:$ORIGIN_PORT"
scheme = "http"

[[routes]]
name = "catch_all"
upstream = "origin"

[routes.match]
path = "/"
TOML

stage "Starting postrust-proxy on 0.0.0.0:$PORT"
"$BIN" "$WORK/h2spec.toml" >"$WORK/proxy.log" 2>&1 &
echo $! > "$WORK/proxy.pid"
disown

# Wait for the listener rather than sleeping a guessed interval.
for _ in $(seq 1 40); do
    grep -q "listening" "$WORK/proxy.log" 2>/dev/null && break
    sleep 0.25
done
grep -q "listening" "$WORK/proxy.log" || { cat "$WORK/proxy.log"; die "proxy did not start"; }
if [ -n "$H2_PORT" ]; then
    for _ in $(seq 1 40); do
        grep -q "HTTP/2-only proxy listening" "$WORK/proxy.log" 2>/dev/null && break
        sleep 0.25
    done
    grep -q "HTTP/2-only proxy listening" "$WORK/proxy.log" \
        || { cat "$WORK/proxy.log"; die "http2 listener did not start"; }
fi

TARGET_PORT="${H2_PORT:-$PORT}"
if [ -n "$H2_PORT" ]; then
    stage "Running h2spec against the HTTP/2-only port $TARGET_PORT"
else
    stage "Running h2spec against the shared h1/h2c port $TARGET_PORT"
fi
docker run --rm "$IMAGE" -h host.docker.internal -p "$TARGET_PORT" "$@" 2>&1 \
    | tee "$WORK/h2spec.log"

stage "Summary"
grep -E "^[0-9]+ tests, " "$WORK/h2spec.log" \
    || printf '(no summary line -- see %s)\n' "$WORK/h2spec.log"
printf 'full log:  %s\n' "$WORK/h2spec.log"
printf 'proxy log: %s\n' "$WORK/proxy.log"
