#!/usr/bin/env bash
# Run the Autobahn WebSocket test suite through postrust-proxy.
#
# Autobahn (https://github.com/crossbario/autobahn-testsuite) is the reference
# conformance suite for RFC 6455. Topology:
#
#   fuzzingclient (docker) -> postrust-proxy (native) -> echoserver (docker)
#
# Both ends are Autobahn's own, so any non-OK case is about the proxy's tunnel
# rather than about the endpoints disagreeing. This is the sharper of the two
# HTTP/2-and-upgrade suites for us: postrust does not parse WebSocket frames, it
# splices two upgraded streams, so what is under test is whether that splice is
# faithful under fragmentation, large payloads, and the close handshake.
#
# The proxy runs natively and only Autobahn runs in Docker, reaching the host
# via host.docker.internal, so no Rust image build is needed.
#
# Usage:
#   scripts/autobahn/run.sh                    # whole suite
#   CASES='["1.*","2.*"]' scripts/autobahn/run.sh
#   PORT=9080 scripts/autobahn/run.sh
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
PORT="${PORT:-9080}"
ORIGIN_PORT="${ORIGIN_PORT:-9002}"
IMAGE="${AUTOBAHN_IMAGE:-crossbario/autobahn-testsuite:latest}"
WORK="$HERE/.work"
REPORTS="$HERE/reports"

# Default to the whole suite. Anything narrower is reported below, because a
# partial run that looks like a full pass is worse than no run at all.
CASES="${CASES:-[\"*\"]}"
# BASELINE=1 runs Autobahn straight at the echoserver, no proxy in the path.
# Non-OK results that appear in BOTH runs are properties of the origin, not of
# the tunnel -- which matters here because postrust never inspects WebSocket
# frames, so most of what Autobahn scores is the endpoint behind it.
BASELINE="${BASELINE:-0}"
EXCLUDE_CASES="${EXCLUDE_CASES:-[]}"

die() { printf 'error: %s\n' "$1" >&2; exit 1; }
stage() { printf '\n==> %s\n' "$1"; }

command -v docker >/dev/null || die "docker not found"
mkdir -p "$WORK" "$REPORTS"

cleanup() {
    if [ -f "$WORK/proxy.pid" ]; then
        kill "$(cat "$WORK/proxy.pid")" 2>/dev/null
        rm -f "$WORK/proxy.pid"
    fi
    docker rm -f autobahn-echoserver >/dev/null 2>&1
}
trap cleanup EXIT

stage "Building postrust-proxy"
( cd "$ROOT" && cargo build -p postrust-proxy 2>&1 | tail -3 ) || die "build failed"
BIN="$ROOT/target/debug/postrust-proxy"
[ -x "$BIN" ] || die "no binary at $BIN"

stage "Starting Autobahn echoserver on 127.0.0.1:$ORIGIN_PORT"
docker rm -f autobahn-echoserver >/dev/null 2>&1
docker run -d --name autobahn-echoserver -p "$ORIGIN_PORT:9002" "$IMAGE" \
    wstest -m echoserver -w "ws://0.0.0.0:9002" >/dev/null \
    || die "could not start the echoserver"

for _ in $(seq 1 60); do
    if docker logs autobahn-echoserver 2>&1 | grep -qi "listening\|running\|site starting"; then
        break
    fi
    sleep 0.5
done

cat > "$WORK/autobahn.toml" <<TOML
# Generated by scripts/autobahn/run.sh
[server]
http_host = "0.0.0.0"
http_port = $PORT

[[upstreams]]
name = "ws_echo"

[[upstreams.backends]]
address = "127.0.0.1:$ORIGIN_PORT"
scheme = "http"

[[routes]]
name = "catch_all"
upstream = "ws_echo"

[routes.match]
path = "/"
TOML

if [ "$BASELINE" = "1" ]; then
    stage "BASELINE run: bypassing the proxy, targeting the echoserver directly"
    TARGET_PORT="$ORIGIN_PORT"
    AGENT="echoserver-direct"
    REPORTS="$HERE/reports-baseline"
    mkdir -p "$REPORTS"
else
    stage "Starting postrust-proxy on 0.0.0.0:$PORT"
    "$BIN" "$WORK/autobahn.toml" >"$WORK/proxy.log" 2>&1 &
    echo $! > "$WORK/proxy.pid"
    disown

    for _ in $(seq 1 40); do
        grep -q "listening" "$WORK/proxy.log" 2>/dev/null && break
        sleep 0.25
    done
    grep -q "listening" "$WORK/proxy.log" || { cat "$WORK/proxy.log"; die "proxy did not start"; }
    TARGET_PORT="$PORT"
    AGENT="postrust-proxy"
fi

cat > "$WORK/fuzzingclient.json" <<JSON
{
  "outdir": "/reports",
  "servers": [
    {
      "agent": "$AGENT",
      "url": "ws://host.docker.internal:$TARGET_PORT/chat"
    }
  ],
  "cases": $CASES,
  "exclude-cases": $EXCLUDE_CASES,
  "exclude-agent-cases": {}
}
JSON

if [ "$CASES" != '["*"]' ] || [ "$EXCLUDE_CASES" != "[]" ]; then
    printf '\nNOTE: this is a PARTIAL run -- cases=%s exclude=%s\n' "$CASES" "$EXCLUDE_CASES"
fi

stage "Running the Autobahn fuzzingclient"
docker run --rm \
    -v "$WORK:/config" \
    -v "$REPORTS:/reports" \
    "$IMAGE" \
    wstest -m fuzzingclient -s /config/fuzzingclient.json 2>&1 \
    | tail -20

stage "Summary"
BASELINE_REPORT="$HERE/reports-baseline/index.json"
if [ -f "$REPORTS/index.json" ]; then
    # Pass the baseline when one exists: it turns on the regression check, which
    # is the only rule that really speaks to the tunnel.
    if [ "$BASELINE" != "1" ] && [ -f "$BASELINE_REPORT" ]; then
        python3 "$HERE/summarize.py" "$REPORTS/index.json" "$BASELINE_REPORT"
    else
        python3 "$HERE/summarize.py" "$REPORTS/index.json"
    fi
    SUMMARY_STATUS=$?
else
    printf 'no report at %s\n' "$REPORTS/index.json"
    SUMMARY_STATUS=1
fi

printf 'html report: %s/index.html\n' "$REPORTS"
printf 'proxy log:   %s\n' "$WORK/proxy.log"
exit $SUMMARY_STATUS
